options:
  logging: 'CLOUD_LOGGING_ONLY'

substitutions:
  _CONTAINER_REGISTRY: "afterhours-services"
  _SERVICE_IMAGE: "afterhours_merchant"
  _ARTIFACT_REGISTRY: "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_CONTAINER_REGISTRY}/${_SERVICE_IMAGE}:${COMMIT_SHA}"
  _ARTIFACT_BASE: "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_CONTAINER_REGISTRY}/${_SERVICE_IMAGE}"

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/afterhours-build-private-ssh-key/versions/latest"
      env: "SSH_PRIVATE_KEY"

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    secretEnv: ["SSH_PRIVATE_KEY"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo "$$SSH_PRIVATE_KEY" >> /root/.ssh/id_rsa
        chmod 400 /root/.ssh/id_rsa
        ssh-keyscan github.com >> /root/.ssh/known_hosts
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: 'docker:24.0'
    entrypoint: "sh"
    args:
      - -c
      - |
        eval $(ssh-agent)
        ssh-add /root/.ssh/id_rsa
        DOCKER_BUILDKIT=1 docker build --ssh=default -t $_ARTIFACT_REGISTRY .
    volumes:
      - name: "ssh"
        path: /root/.ssh

  - name: 'gcr.io/cloud-builders/docker'
    args: [push, "$_ARTIFACT_REGISTRY"]

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: "bash"
    args:
      - -c
      - |
        git clone git@github.com:Dine-Resturant-Reservation/services_gke_production.git /repo
    volumes:
      - name: "ssh"
        path: /root/.ssh
      - name: "repo"
        path: /repo

  - name: 'k8s.gcr.io/kustomize/kustomize:v5.0.1'
    entrypoint: sh
    args:
      - -c
      - |
        cd /repo/overlays/dev
        kustomize edit set image $_ARTIFACT_BASE=$_ARTIFACT_REGISTRY
    volumes:
      - name: 'repo'
        path: /repo

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: "bash"
    args:
      - -c
      - |
        cd /repo
        git config --global user.email "sadegh.b218@gmail.com"
        git config --global user.name "BerserkerMother"
        git add overlays/dev/kustomization.yaml
        git commit -m "repo:$REPO_NAME commit_sha:$SHORT_SHA"
        git push origin main
    volumes:
      - name: "ssh"
        path: /root/.ssh
      - name: "repo"
        path: /repo
